"""
Mock data for all 8 Indian game stores.
This data simulates real scraping results and is used during development.
When Firecrawl integration is enabled, this module will be bypassed.
"""

# Mock game catalog with prices across all 8 stores
# Each entry has: store_name, title variants, new_price, preowned_price, url, image_url, in_stock
MOCK_GAME_CATALOG = {
    "god of war ragnarok": {
        "GamesTheShop": {
            "title": "God of War Ragnarök - PS5",
            "new_price": 3999.0,
            "original_price": 4999.0,
            "preowned_price": 2799.0,
            "url": "https://www.gamestheshop.com/god-of-war-ragnarok-ps5",
            "image_url": "https://placeholder.co/300x400?text=GoW+Ragnarok",
            "in_stock": True,
        },
        "GameNation": {
            "title": "God of War Ragnarök (PS5)",
            "new_price": 3799.0,
            "original_price": 4999.0,
            "preowned_price": 2599.0,
            "url": "https://www.gamenation.in/god-of-war-ragnarok",
            "image_url": "https://placeholder.co/300x400?text=GoW+Ragnarok",
            "in_stock": True,
        },
        "Amazon.in": {
            "title": "God of War Ragnarök - PlayStation 5",
            "new_price": 3499.0,
            "original_price": 4999.0,
            "preowned_price": None,
            "url": "https://www.amazon.in/God-War-Ragnarok-PS5/dp/B0B6194QMK",
            "image_url": "https://placeholder.co/300x400?text=GoW+Ragnarok",
            "in_stock": True,
        },
        "Flipkart": {
            "title": "God of War Ragnarök (PS5)",
            "new_price": 3699.0,
            "original_price": 4999.0,
            "preowned_price": None,
            "url": "https://www.flipkart.com/god-of-war-ragnarok",
            "image_url": "https://placeholder.co/300x400?text=GoW+Ragnarok",
            "in_stock": True,
        },
        "Mcube Games": {
            "title": "God Of War Ragnarok PS5",
            "new_price": 3899.0,
            "original_price": 4999.0,
            "preowned_price": 2699.0,
            "url": "https://mcubegames.com/god-of-war-ragnarok",
            "image_url": "https://placeholder.co/300x400?text=GoW+Ragnarok",
            "in_stock": True,
        },
        "GameShort.in": {
            "title": "God of War Ragnarök PS5",
            "new_price": 4099.0,
            "original_price": 4999.0,
            "preowned_price": 2899.0,
            "url": "https://gameshort.in/god-of-war-ragnarok",
            "image_url": "https://placeholder.co/300x400?text=GoW+Ragnarok",
            "in_stock": True,
        },
        "Dacby": {
            "title": "God of War Ragnarök - PS5",
            "new_price": 4199.0,
            "original_price": 4999.0,
            "preowned_price": 2999.0,
            "url": "https://dacby.com/god-of-war-ragnarok",
            "image_url": "https://placeholder.co/300x400?text=GoW+Ragnarok",
            "in_stock": True,
        },
        "HG World": {
            "title": "God of War Ragnarök PS5",
            "new_price": 4299.0,
            "original_price": 4999.0,
            "preowned_price": 3099.0,
            "url": "https://hgworld.in/god-of-war-ragnarok",
            "image_url": "https://placeholder.co/300x400?text=GoW+Ragnarok",
            "in_stock": True,
        },
    },
    "spider-man 2": {
        "GamesTheShop": {
            "title": "Marvel's Spider-Man 2 - PS5",
            "new_price": 3499.0,
            "original_price": 4999.0,
            "preowned_price": 2499.0,
            "url": "https://www.gamestheshop.com/spiderman-2-ps5",
            "image_url": "https://placeholder.co/300x400?text=SpiderMan+2",
            "in_stock": True,
        },
        "GameNation": {
            "title": "Marvel's Spider-Man 2 (PS5)",
            "new_price": 3299.0,
            "original_price": 4999.0,
            "preowned_price": 2299.0,
            "url": "https://www.gamenation.in/spiderman-2",
            "image_url": "https://placeholder.co/300x400?text=SpiderMan+2",
            "in_stock": True,
        },
        "Amazon.in": {
            "title": "Marvel's Spider-Man 2 - PlayStation 5",
            "new_price": 2999.0,
            "original_price": 4999.0,
            "preowned_price": None,
            "url": "https://www.amazon.in/Spiderman-2-PS5/dp/B0CG1KQ9NF",
            "image_url": "https://placeholder.co/300x400?text=SpiderMan+2",
            "in_stock": True,
        },
        "Flipkart": {
            "title": "Marvel's Spider-Man 2 (PS5)",
            "new_price": 3199.0,
            "original_price": 4999.0,
            "preowned_price": None,
            "url": "https://www.flipkart.com/spiderman-2-ps5",
            "image_url": "https://placeholder.co/300x400?text=SpiderMan+2",
            "in_stock": True,
        },
        "Mcube Games": {
            "title": "Spider-Man 2 PS5",
            "new_price": 3399.0,
            "original_price": 4999.0,
            "preowned_price": 2399.0,
            "url": "https://mcubegames.com/spiderman-2",
            "image_url": "https://placeholder.co/300x400?text=SpiderMan+2",
            "in_stock": True,
        },
        "GameShort.in": {
            "title": "Marvel's Spider-Man 2 PS5",
            "new_price": 3599.0,
            "original_price": 4999.0,
            "preowned_price": 2599.0,
            "url": "https://gameshort.in/spiderman-2",
            "image_url": "https://placeholder.co/300x400?text=SpiderMan+2",
            "in_stock": True,
        },
        "Dacby": {
            "title": "Spider-Man 2 - PS5",
            "new_price": 3699.0,
            "original_price": 4999.0,
            "preowned_price": 2699.0,
            "url": "https://dacby.com/spiderman-2",
            "image_url": "https://placeholder.co/300x400?text=SpiderMan+2",
            "in_stock": True,
        },
        "HG World": {
            "title": "Spider-Man 2 PS5",
            "new_price": 3799.0,
            "original_price": 4999.0,
            "preowned_price": 2799.0,
            "url": "https://hgworld.in/spiderman-2",
            "image_url": "https://placeholder.co/300x400?text=SpiderMan+2",
            "in_stock": True,
        },
    },
    "elden ring": {
        "GamesTheShop": {
            "title": "Elden Ring - PS5",
            "new_price": 2999.0,
            "original_price": 3999.0,
            "preowned_price": 1999.0,
            "url": "https://www.gamestheshop.com/elden-ring-ps5",
            "image_url": "https://placeholder.co/300x400?text=Elden+Ring",
            "in_stock": True,
        },
        "GameNation": {
            "title": "Elden Ring (PS5)",
            "new_price": 2799.0,
            "original_price": 3999.0,
            "preowned_price": 1799.0,
            "url": "https://www.gamenation.in/elden-ring",
            "image_url": "https://placeholder.co/300x400?text=Elden+Ring",
            "in_stock": True,
        },
        "Amazon.in": {
            "title": "Elden Ring - PlayStation 5",
            "new_price": 2499.0,
            "original_price": 3999.0,
            "preowned_price": None,
            "url": "https://www.amazon.in/Elden-Ring-PS5/dp/B09KYGZ77P",
            "image_url": "https://placeholder.co/300x400?text=Elden+Ring",
            "in_stock": True,
        },
        "Flipkart": {
            "title": "Elden Ring (PS5)",
            "new_price": 2699.0,
            "original_price": 3999.0,
            "preowned_price": None,
            "url": "https://www.flipkart.com/elden-ring-ps5",
            "image_url": "https://placeholder.co/300x400?text=Elden+Ring",
            "in_stock": True,
        },
        "Mcube Games": {
            "title": "Elden Ring PS5",
            "new_price": 2899.0,
            "original_price": 3999.0,
            "preowned_price": 1899.0,
            "url": "https://mcubegames.com/elden-ring",
            "image_url": "https://placeholder.co/300x400?text=Elden+Ring",
            "in_stock": True,
        },
        "GameShort.in": {
            "title": "Elden Ring PS5",
            "new_price": 3099.0,
            "original_price": 3999.0,
            "preowned_price": 2099.0,
            "url": "https://gameshort.in/elden-ring",
            "image_url": "https://placeholder.co/300x400?text=Elden+Ring",
            "in_stock": True,
        },
        "Dacby": {
            "title": "Elden Ring - PS5",
            "new_price": 3199.0,
            "original_price": 3999.0,
            "preowned_price": 2199.0,
            "url": "https://dacby.com/elden-ring",
            "image_url": "https://placeholder.co/300x400?text=Elden+Ring",
            "in_stock": True,
        },
        "HG World": {
            "title": "Elden Ring PS5",
            "new_price": 3299.0,
            "original_price": 3999.0,
            "preowned_price": 2299.0,
            "url": "https://hgworld.in/elden-ring",
            "image_url": "https://placeholder.co/300x400?text=Elden+Ring",
            "in_stock": True,
        },
    },
    "the last of us part i": {
        "GamesTheShop": {
            "title": "The Last of Us Part I - PS5",
            "new_price": 3499.0,
            "original_price": 4999.0,
            "preowned_price": 2499.0,
            "url": "https://www.gamestheshop.com/the-last-of-us-part-i-ps5",
            "image_url": "https://placeholder.co/300x400?text=TLOU+Part+I",
            "in_stock": True,
        },
        "GameNation": {
            "title": "The Last of Us Part I (PS5)",
            "new_price": 3299.0,
            "original_price": 4999.0,
            "preowned_price": 2299.0,
            "url": "https://www.gamenation.in/the-last-of-us-part-i",
            "image_url": "https://placeholder.co/300x400?text=TLOU+Part+I",
            "in_stock": True,
        },
        "Amazon.in": {
            "title": "The Last of Us Part I - PlayStation 5",
            "new_price": 2999.0,
            "original_price": 4999.0,
            "preowned_price": None,
            "url": "https://www.amazon.in/Last-Us-Part-I-PS5/dp/B0B3QV2ZBK",
            "image_url": "https://placeholder.co/300x400?text=TLOU+Part+I",
            "in_stock": True,
        },
        "Flipkart": {
            "title": "The Last of Us Part I (PS5)",
            "new_price": 3199.0,
            "original_price": 4999.0,
            "preowned_price": None,
            "url": "https://www.flipkart.com/the-last-of-us-part-i",
            "image_url": "https://placeholder.co/300x400?text=TLOU+Part+I",
            "in_stock": True,
        },
        "Mcube Games": {
            "title": "The Last of Us Part I PS5",
            "new_price": 3399.0,
            "original_price": 4999.0,
            "preowned_price": 2399.0,
            "url": "https://mcubegames.com/the-last-of-us-part-i",
            "image_url": "https://placeholder.co/300x400?text=TLOU+Part+I",
            "in_stock": True,
        },
        "GameShort.in": {
            "title": "The Last of Us Part I PS5",
            "new_price": 3599.0,
            "original_price": 4999.0,
            "preowned_price": 2599.0,
            "url": "https://gameshort.in/the-last-of-us-part-i",
            "image_url": "https://placeholder.co/300x400?text=TLOU+Part+I",
            "in_stock": True,
        },
        "Dacby": {
            "title": "The Last of Us Part I - PS5",
            "new_price": 3699.0,
            "original_price": 4999.0,
            "preowned_price": 2699.0,
            "url": "https://dacby.com/the-last-of-us-part-i",
            "image_url": "https://placeholder.co/300x400?text=TLOU+Part+I",
            "in_stock": True,
        },
        "HG World": {
            "title": "The Last of Us Part I PS5",
            "new_price": 3799.0,
            "original_price": 4999.0,
            "preowned_price": 2799.0,
            "url": "https://hgworld.in/the-last-of-us-part-i",
            "image_url": "https://placeholder.co/300x400?text=TLOU+Part+I",
            "in_stock": True,
        },
    },
    "fc 25": {
        "GamesTheShop": {
            "title": "EA Sports FC 25 - PS5",
            "new_price": 3999.0,
            "original_price": 4499.0,
            "preowned_price": 2999.0,
            "url": "https://www.gamestheshop.com/fc-25-ps5",
            "image_url": "https://placeholder.co/300x400?text=FC+25",
            "in_stock": True,
        },
        "GameNation": {
            "title": "EA Sports FC 25 (PS5)",
            "new_price": 3799.0,
            "original_price": 4499.0,
            "preowned_price": 2799.0,
            "url": "https://www.gamenation.in/fc-25",
            "image_url": "https://placeholder.co/300x400?text=FC+25",
            "in_stock": True,
        },
        "Amazon.in": {
            "title": "EA SPORTS FC 25 - PlayStation 5",
            "new_price": 3499.0,
            "original_price": 4499.0,
            "preowned_price": None,
            "url": "https://www.amazon.in/EA-Sports-FC-25-PS5/dp/B0DB6TJWXZ",
            "image_url": "https://placeholder.co/300x400?text=FC+25",
            "in_stock": True,
        },
        "Flipkart": {
            "title": "EA Sports FC 25 (PS5)",
            "new_price": 3699.0,
            "original_price": 4499.0,
            "preowned_price": None,
            "url": "https://www.flipkart.com/ea-sports-fc-25",
            "image_url": "https://placeholder.co/300x400?text=FC+25",
            "in_stock": True,
        },
        "Mcube Games": {
            "title": "FC 25 PS5",
            "new_price": 3899.0,
            "original_price": 4499.0,
            "preowned_price": 2899.0,
            "url": "https://mcubegames.com/fc-25",
            "image_url": "https://placeholder.co/300x400?text=FC+25",
            "in_stock": True,
        },
        "GameShort.in": {
            "title": "EA Sports FC 25 PS5",
            "new_price": 4099.0,
            "original_price": 4499.0,
            "preowned_price": 3099.0,
            "url": "https://gameshort.in/fc-25",
            "image_url": "https://placeholder.co/300x400?text=FC+25",
            "in_stock": True,
        },
        "Dacby": {
            "title": "EA Sports FC 25 - PS5",
            "new_price": 4199.0,
            "original_price": 4499.0,
            "preowned_price": 3199.0,
            "url": "https://dacby.com/fc-25",
            "image_url": "https://placeholder.co/300x400?text=FC+25",
            "in_stock": True,
        },
        "HG World": {
            "title": "EA Sports FC 25 PS5",
            "new_price": 4299.0,
            "original_price": 4499.0,
            "preowned_price": 3299.0,
            "url": "https://hgworld.in/fc-25",
            "image_url": "https://placeholder.co/300x400?text=FC+25",
            "in_stock": True,
        },
    },
}

# List of all supported store names
SUPPORTED_STORES = [
    "GamesTheShop",
    "GameNation",
    "Amazon.in",
    "Flipkart",
    "Mcube Games",
    "GameShort.in",
    "Dacby",
    "HG World",
]
